"use strict";

export const menuItems = [
  {
    id: 1,
    parentId: 0,
    text: "General Settings",
    url: "/administrator/general-settings",
    role: ["admin"],
    hasChild: false,
    valid: 0,
    icon: "../assets/images/menu-icons/pra-manager.svg",
    activeIcon: "../assets/images/menu-icons/pra-manager-active.svg",
    isOpened: false,
  },
  {
    id: 2,
    parentId: 0,
    text: "Homepage Settings",
    url: "/administrator/homepage-settings",
    role: ["admin"],
    hasChild: false,
    valid: 0,
    icon: "../assets/images/menu-icons/pra-manager.svg",
    activeIcon: "../assets/images/menu-icons/pra-manager-active.svg",
    isOpened: false,
  },
  {
    id: 3,
    parentId: 0,
    text: "Store Menu",
    url: "/administrator/store-menu",
    role: ["admin"],
    hasChild: true,
    valid: 0,
    icon: "add",
    activeIcon: "remove",
    isOpened: false,
  },
  {
    id: 4,
    parentId: 0,
    text: "Image Gallery",
    url: "/administrator/image-gallery",
    role: ["admin"],
    hasChild: false,
    valid: 0,
    icon: "../assets/images/menu-icons/pra-manager.svg",
    activeIcon: "../assets/images/menu-icons/pra-manager-active.svg",
    isOpened: false,
  },

  {
    id: 5,
    parentId: 0,
    text: "Specials",
    url: "/administrator/specials",
    role: ["admin"],
    hasChild: false,
    valid: 0,
    icon: "../assets/images/menu-icons/pra-manager.svg",
    activeIcon: "../assets/images/menu-icons/pra-manager-active.svg",
    isOpened: false,
  },
  {
    id: 6,
    parentId: 0,
    text: "Promotion",
    url: "/administrator/promotion",
    role: ["admin"],
    hasChild: false,
    valid: 0,
    icon: "../assets/images/menu-icons/pra-manager.svg",
    activeIcon: "../assets/images/menu-icons/pra-manager-active.svg",
    isOpened: false,
  },
  {
    id: 7,
    parentId: 0,
    text: "Feedback",
    url: "/administrator/feedback",
    role: ["admin"],
    hasChild: false,
    valid: 0,
    icon: "../assets/images/menu-icons/pra-manager.svg",
    activeIcon: "../assets/images/menu-icons/pra-manager-active.svg",
    isOpened: false,
  },
  {
    id: 8,
    parentId: 0,
    text: "Notifications",
    url: "/administrator/notifications",
    role: ["admin"],
    hasChild: false,
    valid: 0,
    icon: "../assets/images/menu-icons/pra-manager.svg",
    activeIcon: "../assets/images/menu-icons/pra-manager-active.svg",
    isOpened: false,
  },
  {
    id: 9,
    parentId: 0,
    text: "Business Setup",
    url: "/administrator/business-setup",
    role: ["admin"],
    hasChild: false,
    valid: 0,
    icon: "../assets/images/menu-icons/pra-manager.svg",
    activeIcon: "../assets/images/menu-icons/pra-manager-active.svg",
    isOpened: false,
  },

  {
    id: 10,
    parentId: 3,
    text: "Sub Store Menu --- 1",
    url: "/administrator/image-gallery",
    role: ["admin"],
    hasChild: false,
    valid: 0,
    icon: "../assets/images/menu-icons/pra-manager.svg",
    activeIcon: "../assets/images/menu-icons/pra-manager-active.svg",
    isOpened: false,
  },
  {
    id: 11,
    parentId: 3,
    text: "Sub Store Menu --- 2",
    url: "/administrator/image-gallery",
    role: ["admin"],
    hasChild: false,
    valid: 0,
    icon: "../assets/images/menu-icons/pra-manager.svg",
    activeIcon: "../assets/images/menu-icons/pra-manager-active.svg",
    isOpened: false,
  },
];
